#!/bin/bash
set -e  # stop on any error
echo "=========================================="
echo "  Matchmaking Backend — Deployment Start"
echo "=========================================="

# ── Config ────────────────────────────────────────────────────────────────────
APP_DIR="/home/ec2-user/mm/MatchmakingApplication"
TOMCAT_WEBAPPS="/opt/tomcat/webapps"
WAR_NAME="matchmaking-0.0.1-SNAPSHOT.war"   # generated by Maven (no finalName set)
DEPLOY_NAME="ROOT.war"                        # deployed as ROOT so it serves on /

# ── Pull latest code ──────────────────────────────────────────────────────────
echo ""
echo "[1/4] Pulling latest code from main..."
cd "$APP_DIR"
git pull origin main

# ── Build ─────────────────────────────────────────────────────────────────────
echo ""
echo "[2/4] Building WAR (skipping tests)..."
MAVEN_OPTS="-Xms256m -Xmx768m" mvn clean package -DskipTests

# Confirm WAR was created
if [ ! -f "target/$WAR_NAME" ]; then
  echo "ERROR: WAR file not found at target/$WAR_NAME — build may have failed."
  exit 1
fi
echo "WAR built successfully: target/$WAR_NAME"

# ── Deploy to Tomcat ──────────────────────────────────────────────────────────
echo ""
echo "[3/4] Deploying to Tomcat..."
sudo systemctl stop tomcat

# Remove old deployment
rm -rf "$TOMCAT_WEBAPPS/ROOT"
rm -f  "$TOMCAT_WEBAPPS/ROOT.war"

# Copy new WAR
cp "target/$WAR_NAME" "$TOMCAT_WEBAPPS/$DEPLOY_NAME"
echo "Copied to $TOMCAT_WEBAPPS/$DEPLOY_NAME"

sudo systemctl start tomcat

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "[4/4] Deployment completed!"
echo "=========================================="
echo "  Tailing Tomcat logs (Ctrl+C to exit)"
echo "=========================================="
tail -f /opt/tomcat/logs/catalina.out
